spring:
  application:
    name: video-convert

  output:
    ansi:
      enabled: ALWAYS

  data:
    mongodb:
      uri:  ${MONGO_URL}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB	

aws:
 access-key: ${AWS_ACCESS_KEY_ID}
 secret-key: ${AWS_SECRET_KEY}
 region:  ${AWS_REGION}
 bucket: ${AWS_BUCKET}

sqs:
  queue:
    url: ${SQS_QUEUE_URL}
  notification:
    queue-url: ${SQS_QUEUE_NOTIFICATION_URL}

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        security.oauth2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: loggers
